### PR TITLE
Accessories

### PR DESCRIPTION
**Pull request by dhh**
Operate accessory services like MySQL and Redis via MRSK.

### CODE REVIEW

**Comment by northeastprince** [comment]
@dhh is this something 37signals is using in production and/or plans to? For something like a big MySQL database this doesn't seem complex enough to be a good solution for managing it.

**Comment by dhh** [comment]
What complexity are you craving?

**Comment by northeastprince** [comment]
Good point 😆, I guess it just seems too simple to handle something like a core database.

**Comment by dhh** [comment]
Why? You mount your data using volumes that you should of course make sure are properly backed up. You can setup multiple, if you want full replication. Complexity does not make something more robust. Quite the contrary.

**Pull request merged**
